### ISSUE TITLE
[improvement] Only show leaderboard scores above 0 points

### ISSUE THREAD

**Issue by maartengo** [1grzyb1/aoc-slack#1]
First of all; thanks for providing this application!

It would be great if the leaderboard only shows participants with points. The leaderboard I currently use has 120+ participants, but not all of them are active. This creates a large Slack post when the leaderboard is displayed.

Instead of showing participants with 0 points, please only show participants with >0 points.

**Comment by 1grzyb1** [comment]
Hi
Thanks for raising the issue.
I added a new feature flag to filter inactive users `AOC_SLACK_ONLY_ACTIVE_USERS`. 
By default, it is set to `false` as I think it's not a standard situation to have 120 users with the most inactive but when you set it to true it will filter inactive one
