### ISSUE TITLE
Failing to start due to null name on member.

### ISSUE THREAD

**Issue by jacobrv** [1grzyb1/aoc-slack#2]
When trying to start the docker container against my friend group's leaderboard, I get an error about name being non-nullable on members. We have an anonymous member in our leaderboard, so it's possible that's where the null is coming from. I created a new private leaderboard with only myself and it runs just fine with no error. I've tried turning on active users only, but that didn't help. Could you make name nullable or perhaps default it to "Anonymous" or something like that? Thanks.

`2023-12-01 19:20:19 Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class ovh.snet.grzybek.aocslack.LeaderBoard$Member] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which is a non-nullable type
2023-12-01 19:20:19  at [Source: (org.springframework.core.io.buffer.DataBufferInputStream); line: 1, column: 1118] (through reference chain: ovh.snet.grzybek.aocslack.LeaderBoard["members"]->java.util.LinkedHashMap["1763430"]->ovh.snet.grzybek.aocslack.LeaderBoard$Member["name"])`

**Comment by 1grzyb1** [comment]
Hi
Thanks for raising an issue!
I didn't even know that it's possible to get a null name.
I pushed fix and now user will be displayed as `"Anonymous user #${id}"`. I only unit tested it so let me know if it will work on your leaderboard

**Comment by jacobrv** [comment]
It works! Thanks!
